#============================================================================================================================| 
#    _____                      .__   __________           .___                     
#   /     \   _________________ |  |__\______   \ ____   __| _/____   ____   _____  
#  /  \ /  \ /  _ \_  __ \____ \|  |  \|       _// __ \ / __ |/ __ \_/ __ \ /     \ 
# /    Y    (  <_> )  | \/  |_> >   Y  \    |   \  ___// /_/ \  ___/\  ___/|  Y Y  \
# \____|__  /\____/|__|  |   __/|___|  /____|_  /\___  >____ |\___  >\___  >__|_|  /
#         \/             |__|        \/       \/     \/     \/    \/     \/      \/ 
#
#============================================================================================================================|
#
# Plugin Version: 1.3.0
# Spigot Link: https://www.spigotmc.org/resources/morphredeem-mcmmo-credits-1-14.67435/
# Discord Link: https://discord.gg/6bnU9xn
# Author's Discord: Morphie#6969
# 
# If you have issues or questions feel free to message me on spigot OR discord.
# Please do keep in mind however that I will respond when I can! <3
#
#============================================================================================================================|

Settings:
  # The color of glass in the main /morphreedem menu.
  BackgroundGlassColor: 11
  # Item to replace disabled Skills with.
  ReplaceGUIItem:
    Enabled: false
    ItemName: STRUCTURE_VOID
  # Enable or disable the plugin credits item in the /morphredeem menu.
  PluginCredits:
    Enabled: true
  # Change the Item types in the main /morphredeem menu.
  GUI:
    mcMMOCredits:
      ItemName: NETHER_STAR
    CreditsSpent:
      ItemName: EMERALD
    PluginCredits:
      ItemName: PAPER

#============================================================================================================================|

# Storage method, can be MySQL or YML
StorageMethod: "YML"

# Requires 'StorageMethod' to be MySQL
MySQL:
  Username: "root"
  Password: "password"
  Host: "localhost"
  Port: 3306
  SSL: false
  Database: "minecraft"
  TablePrefix: "mr_"
  
#============================================================================================================================|

# Skill Prestige System! Allow your players to prestige their mcMMO skill levels when they reach the level cap.
# (This does require you to have a level cap set in mcMMO.) This also allows you to set up a sort of Prestige 'Tree'.
# Meaning the players can prestige a skill X amount of times with the option to make the rewards better every few prestiges.

# Below I will explain how each option works for the prestige system.
# LevelCap: - DEFAULT (Level cap set in mcMMO), or you can set it to a level below the configured mcMMO cap.
# LevelReset: - Level that the skill will be reset too.
# PrestigeCap: - How many times can a user prestige a skill.
Prestige:
  LevelCap: DEFAULT
  Acrobatics:
    LevelReset: 0
    PrestigeCap: 10
  Alchemy:
    LevelReset: 0
    PrestigeCap: 10
  Archery:
    LevelReset: 0
    PrestigeCap: 10
  Axes:
    LevelReset: 0
    PrestigeCap: 10
  Excavation:
    LevelReset: 0
    PrestigeCap: 10
  Fishing:
    LevelReset: 0
    PrestigeCap: 10
  Herbalism:
    LevelReset: 0
    PrestigeCap: 10
  Mining:
    LevelReset: 0
    PrestigeCap: 10
  Repair:
    LevelReset: 0
    PrestigeCap: 10
  Swords:
    LevelReset: 0
    PrestigeCap: 10
  Taming:
    LevelReset: 0
    PrestigeCap: 10
  Unarmed:
    LevelReset: 0
    PrestigeCap: 10
  Woodcutting:
    LevelReset: 0
    PrestigeCap: 10

#============================================================================================================================|